[[redirects]]
    from = "/zapquake-calculator"
    to = "/html/zapquake-calculator"
    status = 200
    force = true

[[redirects]]
    from = "/html/zapquake-calculator"
    to = "/zapquake-calculator"
    force = true