[[redirects]]
    from = "/"
    to = "/"
    status = 301
    force = true

[[redirects]]
    from = "/*"
    to = "/html/:splat"
    status = 200
    force = true

[[redirects]]
    from = "/html/*"
    to = "/:splat"
    force = true