[[redirects]]
    from = "/html/*"
    to = "/:splat"

[[redirects]]
    from = "/*"
    to = "/html/:splat"
    status = 200

#[[redirects]]
#    from = "/*"
#    to = "/html/*"
#    status = 200
#    force = true

